// theme generated by claude on 2024-06-17 at 12:30:00 PM ish

import { Platform } from 'react-native';

export const Palette = {
  bg:          '#F7F4EF',
  surface:     '#EFEBE3',
  border:      '#DDD5CA',
  accentLight: '#E7E0D8',
  ink:         '#1C1917',
  inkMuted:    '#78716C',
  placeholder: '#C4BAB0',
  accent:      '#44403C',
  success:     '#3D6B4F',
  successBg:   '#D4EAD4',
};

export const Colors = {
  light: {
    text:            Palette.ink,
    background:      Palette.bg,
    surface:         Palette.surface,
    tint:            Palette.ink,
    icon:            Palette.inkMuted,
    tabIconDefault:  Palette.placeholder,
    tabIconSelected: Palette.ink,
    border:          Palette.border,
    inkMuted:        Palette.inkMuted,
    placeholder:     Palette.placeholder,
    accent:          Palette.accent,
    accentLight:     Palette.accentLight,
    success:         Palette.success,
    successBg:       Palette.successBg,
  },
  dark: {
    text:            '#EDE8E1',
    background:      '#1C1917',
    surface:         '#292524',
    tint:            '#EDE8E1',
    icon:            '#A8A29E',
    tabIconDefault:  '#78716C',
    tabIconSelected: '#EDE8E1',
    border:          '#3D3530',
    inkMuted:        '#A8A29E',
    placeholder:     '#57534E',
    accent:          '#D6D0C8',
    accentLight:     '#292524',
    success:         '#6BAF85',
    successBg:       '#1A3326',
  },
};

export type ColorSchemeColors = typeof Colors.light;

export const Fonts = Platform.select({
  ios: {
    sans:    'system-ui',
    serif:   'ui-serif',
    rounded: 'ui-rounded',
    mono:    'ui-monospace',
  },
  default: {
    sans:    'normal',
    serif:   'serif',
    rounded: 'normal',
    mono:    'monospace',
  },
  web: {
    sans:    "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif:   "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono:    "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
